<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<Nullable>enable</Nullable>
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>false</SelfContained>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Core\Core.csproj" />
	  <ProjectReference Include="..\Portal\Portal.csproj">
		<Private>false</Private>
		<CopyLocal>false</CopyLocal>
		</ProjectReference>
	</ItemGroup>

</Project>