<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<PlatformTarget>AnyCPU</PlatformTarget>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<ExcelDnaCreate32BitAddIn>true</ExcelDnaCreate32BitAddIn>
		<ExcelDnaCreate64BitAddIn>true</ExcelDnaCreate64BitAddIn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ExcelDna.AddIn" Version="1.9.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Core\Core.csproj" />
	</ItemGroup>
</Project>